#Eureka server服务端⼝
server:
  port: 8761
spring:
  application:
    name: lagou-cloud-eureka-server # 应⽤名称，会在Eureka中作为服务的id标识（serviceId） 集群模式 保持一致

    # Eureka 客户端配置（和Server交互） eureka server本质上 也是一个client 客户端
eureka:
  # 主机名
  instance:
    hostname: LagouCloudEurekaServerA
  client:
    service-url: # 客户端与EurekaServer交互的地址，如果是集群，也需要写其它Server的地址
      defaultZone: http://LagouCloudEurekaServerB:8762/eureka/
    register-with-eureka: true # 自己就是服务不需要注册自己,集群模式 true
    fetch-registry: true #自己就是服务不需要从Eureka Server获取服务信息,默认为true，置为false 集群模式 true